import { deflateRawSync } from 'node:zlib'

const CRC32_TABLE = (() => {
  const table = new Uint32Array(256)
  for (let index = 0; index < 256; index += 1) {
    let value = index
    for (let bit = 0; bit < 8; bit += 1) {
      value = value & 1 ? 0xedb88320 ^ (value >>> 1) : value >>> 1
    }
    table[index] = value >>> 0
  }
  return table
})()

function crc32(bytes: Uint8Array): number {
  let crc = 0xffffffff
  for (let index = 0; index < bytes.length; index += 1) {
    crc = CRC32_TABLE[(crc ^ bytes[index]) & 0xff] ^ (crc >>> 8)
  }
  return (crc ^ 0xffffffff) >>> 0
}

export interface ZipFixtureFile {
  path: string
  content: string
}

function appendUint16(bytes: number[], value: number): void {
  bytes.push(value & 0xff, (value >>> 8) & 0xff)
}

function appendUint32(bytes: number[], value: number): void {
  bytes.push(value & 0xff, (value >>> 8) & 0xff, (value >>> 16) & 0xff, (value >>> 24) & 0xff)
}

/**
 * Builds a realistic deflated ZIP archive in memory, mirroring the layout produced
 * by the `zip` CLI used by the other E2E fixtures.
 */
export function createZipBuffer(files: ZipFixtureFile[]): Buffer {
  const chunks: number[] = []
  const centralDirectory: number[] = []
  const encoder = new TextEncoder()

  for (const file of files) {
    const nameBytes = encoder.encode(file.path)
    const rawBytes = encoder.encode(file.content)
    const compressed = deflateRawSync(rawBytes)
    const localHeaderOffset = chunks.length

    appendUint32(chunks, 0x04034b50)
    appendUint16(chunks, 20)
    appendUint16(chunks, 0)
    appendUint16(chunks, 8)
    appendUint16(chunks, 0)
    appendUint16(chunks, 0)
    appendUint32(chunks, crc32(rawBytes))
    appendUint32(chunks, compressed.length)
    appendUint32(chunks, rawBytes.length)
    appendUint16(chunks, nameBytes.length)
    appendUint16(chunks, 0)
    chunks.push(...nameBytes)
    chunks.push(...compressed)

    appendUint32(centralDirectory, 0x02014b50)
    appendUint16(centralDirectory, 20)
    appendUint16(centralDirectory, 20)
    appendUint16(centralDirectory, 0)
    appendUint16(centralDirectory, 8)
    appendUint16(centralDirectory, 0)
    appendUint16(centralDirectory, 0)
    appendUint32(centralDirectory, crc32(rawBytes))
    appendUint32(centralDirectory, compressed.length)
    appendUint32(centralDirectory, rawBytes.length)
    appendUint16(centralDirectory, nameBytes.length)
    appendUint16(centralDirectory, 0)
    appendUint16(centralDirectory, 0)
    appendUint16(centralDirectory, 0)
    appendUint16(centralDirectory, 0)
    appendUint32(centralDirectory, 0)
    appendUint32(centralDirectory, localHeaderOffset)
    centralDirectory.push(...nameBytes)
  }

  const centralDirectoryOffset = chunks.length
  chunks.push(...centralDirectory)
  const centralDirectorySize = chunks.length - centralDirectoryOffset

  appendUint32(chunks, 0x06054b50)
  appendUint16(chunks, 0)
  appendUint16(chunks, 0)
  appendUint16(chunks, files.length)
  appendUint16(chunks, files.length)
  appendUint32(chunks, centralDirectorySize)
  appendUint32(chunks, centralDirectoryOffset)
  appendUint16(chunks, 0)

  return Buffer.from(chunks)
}

export function skillMdFixture(name: string, description: string, version?: string): string {
  const versionLine = version ? `\nversion: ${version}` : ''
  return `---
name: ${name}
description: ${description}${versionLine}
---

# ${name}

Generated by Playwright E2E.
`
}
